package com.challenge.sports.utils

import android.content.Context
import score.pro.R

object Formatters {

     fun returnKind(kindIndex:String,context: Context):String{
        return when(kindIndex){
            "1"->{
              context.getString(R.string.goal)
            }
            "2"->{
                context.getString(R.string.red_card)
            }
            "3"->{
                context.getString(R.string.yellow_card)
            }
            "7"->{
                context.getString(R.string.penalty_kick)
            }
            "8"->{
                context.getString(R.string.own_goal)
            }
            "9"->{
                context.getString(R.string.two_y_to_red)
            }
            "11"->{
                context.getString(R.string.substitution)
            }
            "13"->{
                context.getString(R.string.missed_pen)
            }
            else->{
                context.getString(R.string.raw)
            }
        }
    }

     fun returnTechnicName(technicIndex:String,context: Context):String{
        return when(technicIndex){
            "1"->{
                context.getString(R.string.tee_off_first)
            }
            "2"->{
                context.getString(R.string.first_corner_kic)
            }
            "3"->{
                context.getString(R.string.first_yellow)
            }
            "4"->{
                context.getString(R.string.number_of_shots)
            }
            "5"->{
                context.getString(R.string.shots_on_tarhet)
            }
            "6"->{
                context.getString(R.string.number_of_fouls)
            }
            "7"->{
                context.getString(R.string.number_of_corners)
            }
            "8"->{
                context.getString(R.string.number_of_corners_ot)
            }
            "9"->{
                context.getString(R.string.free_kicks)
            }
            "10"->{
                context.getString(R.string.number_of_offsides)
            }
            "11"->{
                context.getString(R.string.own_goals)
            }
            "12"->{
                context.getString(R.string.yello_cards)
            }
            "13"->{
                context.getString(R.string.yellow_cards_ot)
            }
            "14"->{
                context.getString(R.string.red_cards)
            }
            "15"->{
                context.getString(R.string.ball_control)
            }
            "16"->{
                context.getString(R.string.header)
            }
            "17"->{
                context.getString(R.string.save_the_ball)
            }
            "18"->{
                context.getString(R.string.goalkeeper_strikes)
            }
            "19"->{
                context.getString(R.string.lose_the_ball)
            }
            "20"->{
                context.getString(R.string.successful_steal)
            }
            "21"->{
                context.getString(R.string.block)
            }
            "22"->{
                context.getString(R.string.long_pass)
            }
            "23"->{
                context.getString(R.string.short_pass)
            }
            "24"->{
                context.getString(R.string.assist)
            }
            "25"->{
                context.getString(R.string.successful_pass)
            }
            "26"->{
                context.getString(R.string.first_sub)
            }
            "27"->{
                context.getString(R.string.last_sub)
            }
            "28"->{
                context.getString(R.string.first_off)
            }
            "29"->{
                context.getString(R.string.last_off)
            }
            "30"->{
                context.getString(R.string.change_num_players)
            }
            "31"->{
                context.getString(R.string.last_corner_kick)
            }
            "32"->{
                context.getString(R.string.last_yello)
            }
            "33"->{
                context.getString(R.string.change_num_players_ot)
            }
            "34"->{
                context.getString(R.string.num_off_ot)
            }
            "35"->{
                context.getString(R.string.miss_goal)
            }
            "36"->{
                context.getString(R.string.middle_column)
            }
            "37"->{
                context.getString(R.string.headers)
            }
            "38"->{
                context.getString(R.string.blocked_shots)
            }
            "39"->{
                context.getString(R.string.tackles)
            }
            "40"->{
                context.getString(R.string.exceeding_times)
            }
            "41"->{
                context.getString(R.string.out_of_bounds)
            }
            "42"->{
                context.getString(R.string.number_of_passes)
            }
            "43"->{
                context.getString(R.string.pass_success_rate)
            }
            "44"->{
                context.getString(R.string.number_of_attacks)
            }
            "45"->{
                context.getString(R.string.dangerous_attacks)
            }
            "46"->{
                context.getString(R.string.half_time_corners)
            }
            "47"->{
                context.getString(R.string.posession)
            }
            else -> {
                "other"
            }
        }
    }

}
